import type { Metadata, Viewport } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

// export const metadata: Metadata = {
//     metadataBase: new URL(''),
//     title: {
//         template: '%s | ',
//         default: '',
//     },
//     description: '',
//     openGraph: {
//         title: '',
//         description: '',
//         url: '',
//         siteName: '',
//         locale: '',
//         type: '',
//     },
//     twitter: {
//         card: '',
//         title: '',
//         description: '',
//         siteId: '',
//         creator: '',
//         creatorId: '',
//     },
//     alternates: {
//         canonical: '',
//     },
// }

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    )
}
